name: template
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.6
  - pip>=19.0.3
  - affine>=2.3.0
  - fiona>=1.7.13
  - gdal=3.0.3
  - geopandas>=0.7.0
  - matplotlib>=3.1.2
  - networkx>=2.4
  - opencv>=4.1
  - pandas>=0.25.3
  - pyproj>=2.1
  - pyyaml=5.2
  - rasterio>=1.0.23
  - requests=2.22.0
  - rtree>=0.9.3
  - tqdm>=4.40.0
  - urllib3>=1.25.7
  - shapely